services:
  backend:
    env_file:
      - ./env/app.env
    environment:
      - R2_BUCKET=enmipueblo-media
    networks:
      web:
        aliases:
          - backend
          - enmipueblo_backend

  frontend:
    env_file:
      - ./env/app.env
    networks:
      web:
        aliases:
          - frontend
          - enmipueblo_frontend

networks:
  web:
    external: true





  frontend:
    env_file:
      - ./env/app.env
    networks:
      web:
        aliases:
          - frontend
          - enmipueblo_frontend

networks:
  web:
    external: true