services:
  backend:
    env_file:
      - ./env/app.env
    networks:
      web:
        aliases:
          - backend
          - enmipueblo_backend

  frontend:
    env_file:
      - ./env/app.env
    networks:
      web:
        aliases:
          - frontend
          - enmipueblo_frontend

networks:
  web:
    external: true